# Generated by Django 5.0.4 on 2024-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
