# Generated by Django 5.0.4 on 2024-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_profile_github_logo_profile_gmail_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo/'),
        ),
    ]
