# Generated by Django 5.0.4 on 2024-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_profile_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
    ]
